### ISSUE TITLE
hello,The detection algorithm does not seem to detect the five fault types

### ISSUE THREAD

**Issue by rainbownmm** [Ivelina-Zhekova/Anomaly-detection-in-PV-system#1]
Thanks for your great work, it is very cool, but I have some small questions about [10] in your code, I don't see that there are five detection algorithms? Maybe I haven't found it yet, and I see that you only have 1 and -1 for label, so I'm not sure where you are referring to the five algorithms? I hope to receive a reply soon, thanks!

**Comment by rainbownmm** [comment]
I see, it turns out that there are 5 detection algorithms in another paper, so how do you code the kind of fault to determine its fault type after detecting it? Let's say it's Ground fault

**Comment by Ivelina-Z** [comment]
Hello,
This model is capable of only detecting if an anomaly is present. After using SHAP for explainability it's possible to see which of the parameters had the most impact for that decision on the model and examine their values.
The reason for not detecting the specific type of anomaly is that the data is not initially annotated. The annotations are made automatically based on some rules and used only for model evaluation.
